SET check_function_bodies = false;
INSERT INTO public.level (value, description) VALUES ('easyeasy', 'even babies can do it');
INSERT INTO public.level (value, description) VALUES ('easymedium', 'babies probably cant, but toddlers definitely can');
INSERT INTO public.level (value, description) VALUES ('easyhard', 'okay, its like elementary stuff');
INSERT INTO public.level (value, description) VALUES ('mediumeasy', 'easy but not');
INSERT INTO public.level (value, description) VALUES ('mediummedium', 'starts to get hot here');
INSERT INTO public.level (value, description) VALUES ('mediumhard', 'its not hard but its definitely not easy');
INSERT INTO public.level (value, description) VALUES ('hardeasy', 'its easy, but for the pros');
INSERT INTO public.level (value, description) VALUES ('hardmedium', 'can college student do it though ?');
INSERT INTO public.level (value, description) VALUES ('hardhard', 'lets freakin'' gooooooooooo');
