-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_datas" add column "is_online" boolean
--  not null default 'false';
